server:
  applicationConnectors:
    - type: http
      port: 37300
  adminConnectors:
    - type: http
      port: 37301

  requestLog:
        appenders:
          - type: file
            currentLogFilename: /var/log/flipkart/pricing/fk-pricing-kaizen/request.log
            archivedLogFilenamePattern: /var/log/flipkart/pricing/fk-pricing-kaizen/request-%d.log.gz
            timeZone: IST

logging:
      level: INFO
      loggers:
        flipkart.apps: INFO
      appenders:
          - type: file
            currentLogFilename: /var/log/flipkart/pricing/fk-pricing-kaizen/kaizen.log
            archive: true
            archivedLogFilenamePattern: /var/log/flipkart/pricing/fk-pricing-kaizen/kaizen-%d.log.gz
            archivedFileCount: 20
            timeZone: IST

database:
  driverClass: "com.mysql.jdbc.Driver"
  user: "root"
  password:
  url: "jdbc:mysql://localhost/pricing_kaizen"
  maxWaitForConnection: 1s
  minSize: 2
  maxSize: 10
  checkConnectionWhileIdle: false
  properties:
          "hibernate.dialect": "org.hibernate.dialect.MySQL5Dialect"
          "hibernate.hbm2ddl.auto": "NONE"
          "hibernate.connection.isolation": "2"
          "hibernate.show_sql": "true"
          "hibernate.use_sql_comments": "true"
          "hibernate.format_sql" : "true"

