#!/bin/bash

[ $# -lt 1 ] && echo "Usage `basename $0` <env>  [-nodeploy/-nobuild]" && exit 1
#echo "not ready yet" && exit
DOMAIN=$1
shift 1
PACKAGE="kaizen"
[ ! -z $1 ] && PACKAGE=$1 && shift 1
case $DOMAIN in 
    nm|stage|stagech|qa)
	TARGET=${DOMAIN}
    ;; 
    *) 
	echo "Target must be nm/eng/sb/vl/stage/mp/mp2/qa" && exit 2
    ;; 
esac

TAG=release/fk-pricing-kaizen/${DOMAIN}-$(date +%Y%m%d-%H%M)${1}
echo "Promoting to $DOMAIN." $TAG 
git tag -m "Promoting to $DOMAIN." $TAG 
git push origin --tags
git push corp --tags
