#!/bin/bash -xe
function die() {
    echo "Error: $1" >&2
    exit 1
}

[ -z "$LOCAL_DIR" ] && die "No base dir specified"
[ -z "$TARGET" ] && die "No package target specified"
[ -z "$INSTALL_BASE" ] && die "No install base specified"
[ -z "$PACKAGE" ] && die "No package name specified"
[ ! -d "$LOCAL_DIR" ] && die "$LOCAL_DIR does not exist"

case "$TARGET" in
    qa) ENV=qa;;
    nm) ENV=nm;;
    stage) ENV=stage;;
    stagech) ENV=stage;;
    *) die "Invalid target: $TARGET"
esac

# Create base dir for debian packaging
DEB_DIR="$LOCAL_DIR/deb"
[ ! -d "$DEB_DIR/DEBIAN" ] && mkdir -p "$DEB_DIR/DEBIAN"
[ ! -d "$DEB_DIR/etc/$PACKAGE" ] && mkdir -p "$DEB_DIR/etc/$PACKAGE"
[ ! -d "$DEB_DIR/var/lib/$PACKAGE" ] && mkdir -p "$DEB_DIR/var/lib/$PACKAGE"
[ ! -d "$DEB_DIR/var/cache/$PACKAGE" ] && mkdir -p "$DEB_DIR/var/cache/$PACKAGE"
[ ! -d "$DEB_DIR/var/log/flipkart/pricing/$PACKAGE" ] && mkdir -p "$DEB_DIR/var/log/flipkart/pricing/$PACKAGE"
[ ! -d "$DEB_DIR/usr/share/$PACKAGE/conf" ] && mkdir -p "$DEB_DIR/usr/share/$PACKAGE/conf"
[ ! -d "$DEB_DIR/usr/share/$PACKAGE/libs" ] && mkdir -p "$DEB_DIR/usr/share/$PACKAGE/libs"

# Installation directories
[ ! -d "$DEB_DIR/etc/init.d" ] && mkdir -p "$DEB_DIR/etc/init.d"

LB_STATUS_DIR=/var/tmp/fk-pricing-kaizen/lb_status
mkdir -p "${DEB_DIR}${LB_STATUS_DIR}"

rm -rf ~fk-ops-build/.ivy2/cache/flipkart*

cp ${LOCAL_DIR}/config/server_config/${ENV}/pricing_kaizen.yaml ${DEB_DIR}/usr/share/$PACKAGE/conf/

# build app
DEF_MAVEN_CMD=/usr/share/fk-ops-maven2/bin/mvn
if [ ! -e $DEF_MAVEN_CMD ] ; then
    DEF_MAVEN_CMD=mvn
fi

MVN_CMD=${MVN_CMD:-$DEF_MAVEN_CMD}
MVN_OPTIONS="--errors"
MVN="$MVN_CMD -U $MVN_OPTIONS"
echo "Running maven with --quiet. I will take a few minutes." 2>&1

echo "$MVN"
JAVA_PATH="/usr/lib/jvm/java-8-oracle"
#Go to the dir and build package.
(cd ${LOCAL_DIR} && JAVA_HOME=${JAVA_PATH} ${MVN} clean install -DincludeScope=runtime -DskipTests)
(cd ${LOCAL_DIR} && ${MVN} dependency:copy-dependencies -DincludeScope=runtime -DskipTests)

mv ${LOCAL_DIR}/service/target/dependency/*.jar ${DEB_DIR}/usr/share/$PACKAGE/libs
mv ${LOCAL_DIR}/service/target/service-*.jar  ${DEB_DIR}/usr/share/$PACKAGE/libs

PROJECT_DIR="$LOCAL_DIR/package"
#copy the init script
cp ${PROJECT_DIR}/etc/init.d/${PACKAGE} ${DEB_DIR}/etc/init.d/${PACKAGE}

#copy all debian related folders
cp -r ${PROJECT_DIR}/DEBIAN/* ${DEB_DIR}/DEBIAN/
cp -r ${PROJECT_DIR}/usr/* ${DEB_DIR}/usr/share/$PACKAGE/
[ $PACKAGE == "fk-pricing-kaizen" ] && rsync -a --exclude=.svn "${PROJECT_DIR}/etc/cron.d/" "${DEB_DIR}/usr/share/$PACKAGE/cron.d"



#Copy sql migrations
#SQLS_DIR="$DEB_DIR/usr/share/$PACKAGE/sqls"
#[ ! -d "$DEB_DIR/usr/share/$PACKAGE/sqls" ] && mkdir -p "$DEB_DIR/usr/share/$PACKAGE/sqls"
#cp -r ${LOCAL_DIR}/sql_migrations/* $SQLS_DIR/



case $PACKAGE in
  fk-pricing-kaizen) PAC_UID=37902;;
  *) die "Unknown package $PACKAGE";;
esac

case $ENV in
    nm) STATSD_URL="retail-sellside-statsd.nm.flipkart.com" ;;
    stage) STATSD_URL="stage-pricing-backend4.ch.flipkart.com" ;;
    qa) STATSD_URL="stage-pricing-backend4.ch.flipkart.com" ;;
    *) STATSD_URL="localhost" ;;
esac


sed -i -e "s/_PACKAGE_/$PACKAGE/g" "${DEB_DIR}/etc/init.d/$PACKAGE"
sed -i -e "s/_EN_/$ENV/g" "${DEB_DIR}/etc/init.d/$PACKAGE"
sed -i -e "s/_PACKAGE_/$PACKAGE/g" "${DEB_DIR}/DEBIAN/prerm"
sed -i -e "s/_PACKAGE_/$PACKAGE/g" "${DEB_DIR}/DEBIAN/control"
sed -i -e "s/_PACKAGE_/$PACKAGE/g" "${DEB_DIR}/DEBIAN/postinst"
sed -i -e "s/_ENV_/$ENV/g" "${DEB_DIR}/DEBIAN/postinst"
sed -i -e "s/_ENV_/$ENV/g" "${DEB_DIR}/DEBIAN/prerm"
sed -i -e "s/_UID_/$PAC_UID/g" "${DEB_DIR}/DEBIAN/postinst"
sed -i -e "s/_STATSDURL_/$STATSD_URL/g" "${DEB_DIR}/DEBIAN/postinst"

