server:
  applicationConnectors:
    - type: http
      port: 37300
  adminConnectors:
    - type: http
      port: 37301

database: 
  driverClass: com.mysql.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost/pricing_kaizen
  maxWaitForConnection: 1s
  minSize: 2
  maxSize: 10
  checkConnectionWhileIdle: false
